(ns clj-z80.opcodes
  (:require [clj-z80.bytes :refer :all]
            [clojure.core.match :refer [match]]))

(defn n?
  [n]
  (let [forbidden-labels #{:a :b :c :d :e :h :l :ixl :ixh :iyl :iyh :r
                           :af :bc :de :hl :ix :iy :sp}]
    (or (number? n)
        (fn? n)
        (and (coll? n)
             (= (count n) 2)
             (contains? #{:low-word :high-word :displacement} (first n)))
        (and (keyword? n)
             (not (contains? forbidden-labels n))))))

(defn assemble-instr-fd
  [instr]
  (match instr
         [:add :iy [:bc]]                          [0xfd 0x09]
         [:add :iy :de]                            [0xfd 0x19]
         [:ld :iy (nn :guard n?)]                  [0xfd 0x21 (lw nn) (hw nn)]
         [:ld [(nn :guard n?)] :iy]                [0xfd 0x22 (lw nn) (hw nn)]
         [:inc :iy]                                [0xfd 0x23]
         [:inc :iyh]                               [0xfd 0x24]
         [:dec :iyh]                               [0xfd 0x25]
         [:ld :iyh (n :guard n?)]                  [0xfd 0x26 (b n)]
         [:add :iy :iy]                            [0xfd 0x29]
         [:ld :iy [(nn :guard n?)]]                [0xfd 0x2a (lw nn) (hw nn)]
         [:dec :iy]                                [0xfd 0x2b]
         [:inc :iyl]                               [0xfd 0x2c]
         [:dec :iyl]                               [0xfd 0x2d]
         [:ld :iyl (n :guard n?)]                  [0xfd 0x2e (b n)]
         [:inc [:iy (n :guard n?)]]                [0xfd 0x34 (b n)]
         [:dec [:iy (n :guard n?)]]                [0xfd 0x35 (b n)]
         [:ld [:iy (n1 :guard n?)] (n2 :guard n?)] [0xfd 0x36 (b n1) (b n2)]
         [:add :iy :sp]                            [0xfd 0x39]
         [:ld :b :iyh]                             [0xfd 0x44]
         [:ld :b :iyl]                             [0xfd 0x45]
         [:ld :b [:iy (n :guard n?)]]              [0xfd 0x46 (b n)]
         [:ld :c :iyh]                             [0xfd 0x4c]
         [:ld :c :iyl]                             [0xfd 0x4d]
         [:ld :c [:iy (n :guard n?)]]              [0xfd 0x4e (b n)]
         [:ld :d :iyh]                             [0xfd 0x54]
         [:ld :d :iyl]                             [0xfd 0x55]
         [:ld :d [:iy (n :guard n?)]]              [0xfd 0x56 (b n)]
         [:ld :e :iyh]                             [0xfd 0x5c]
         [:ld :e :iyl]                             [0xfd 0x5d]
         [:ld :e [:iy (n :guard n?)]]              [0xfd 0x5e (b n)]
         [:ld :iyh :b]                             [0xfd 0x60]
         [:ld :iyh :c]                             [0xfd 0x61]
         [:ld :iyh :d]                             [0xfd 0x62]
         [:ld :iyh :e]                             [0xfd 0x63]
         [:ld :iyh :iyh]                           [0xfd 0x64]
         [:ld :iyh :iyl]                           [0xfd 0x65]
         [:ld :h [:iy (n :guard n?)]]              [0xfd 0x66 (b n)]
         [:ld :iyh :a]                             [0xfd 0x67]
         [:ld :iyl :b]                             [0xfd 0x68]
         [:ld :iyl :c]                             [0xfd 0x69]
         [:ld :iyl :d]                             [0xfd 0x6a]
         [:ld :iyl :e]                             [0xfd 0x6b]
         [:ld :iyl :iyh]                           [0xfd 0x6c]
         [:ld :iyl :iyl]                           [0xfd 0x6d]
         [:ld :l [:iy (n :guard n?)]]              [0xfd 0x6e (b n)]
         [:ld :iyl :a]                             [0xfd 0x6f]
         [:ld [:iy (n :guard n?)] :b]              [0xfd 0x70 (b n)]
         [:ld [:iy (n :guard n?)] :c]              [0xfd 0x71 (b n)]
         [:ld [:iy (n :guard n?)] :d]              [0xfd 0x72 (b n)]
         [:ld [:iy (n :guard n?)] :e]              [0xfd 0x73 (b n)]
         [:ld [:iy (n :guard n?)] :h]              [0xfd 0x74 (b n)]
         [:ld [:iy (n :guard n?)] :l]              [0xfd 0x75 (b n)]
         [:ld [:iy (n :guard n?)] :a]              [0xfd 0x77 (b n)]
         [:ld :a :iyh]                             [0xfd 0x7c]
         [:ld :a :iyl]                             [0xfd 0x7d]
         [:ld :a [:iy (n :guard n?)]]              [0xfd 0x7e (b n)]
         [:add :iyh]                               [0xfd 0x84]
         [:add :iyl]                               [0xfd 0x85]
         [:add [:iy (n :guard n?)]]                [0xfd 0x86 (b n)]
         [:adc :iyh]                               [0xfd 0x8c]
         [:adc :iyl]                               [0xfd 0x8d]
         [:adc [:iy (n :guard n?)]]                [0xfd 0x8e (b n)]
         [:sub :iyh]                               [0xfd 0x94]
         [:sub :iyl]                               [0xfd 0x95]
         [:sub [:iy (n :guard n?)]]                [0xfd 0x96 (b n)]
         [:sbc :iyh]                               [0xfd 0x9c]
         [:sbc :iyl]                               [0xfd 0x9d]
         [:sbc [:iy (n :guard n?)]]                [0xfd 0x9e (b n)]
         [:and :iyh]                               [0xfd 0xa4]
         [:and :iyl]                               [0xfd 0xa5]
         [:and [:iy (n :guard n?)]]                [0xfd 0xa6 (b n)]
         [:xor :iyh]                               [0xfd 0xac]
         [:xor :iyl]                               [0xfd 0xad]
         [:xor [:iy (n :guard n?)]]                [0xfd 0xae (b n)]
         [:or :iyh]                                [0xfd 0xb4]
         [:or :iyl]                                [0xfd 0xb5]
         [:or [:iy (n :guard n?)]]                 [0xfd 0xb6 (b n)]
         [:cp :iyh]                                [0xfd 0xbc]
         [:cp :iyl]                                [0xfd 0xbd]
         [:cp [:iy (n :guard n?)]]                 [0xfd 0xbe (b n)]
         [:rlc [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x00]
         [:rlc [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x01]
         [:rlc [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x02]
         [:rlc [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x03]
         [:rlc [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x04]
         [:rlc [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x05]
         [:rlc [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x06]
         [:rlc [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x07]
         [:rrc [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x08]
         [:rrc [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x09]
         [:rrc [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x0a]
         [:rrc [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x0b]
         [:rrc [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x0c]
         [:rrc [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x0d]
         [:rrc [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x0e]
         [:rrc [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x0f]
         [:rl [:iy (n :guard n?)] :b]              [0xfd 0xcb (b n) 0x10]
         [:rl [:iy (n :guard n?)] :c]              [0xfd 0xcb (b n) 0x11]
         [:rl [:iy (n :guard n?)] :d]              [0xfd 0xcb (b n) 0x12]
         [:rl [:iy (n :guard n?)] :e]              [0xfd 0xcb (b n) 0x13]
         [:rl [:iy (n :guard n?)] :h]              [0xfd 0xcb (b n) 0x14]
         [:rl [:iy (n :guard n?)] :l]              [0xfd 0xcb (b n) 0x15]
         [:rl [:iy (n :guard n?)]]                 [0xfd 0xcb (b n) 0x16]
         [:rl [:iy (n :guard n?)] :a]              [0xfd 0xcb (b n) 0x17]
         [:rr [:iy (n :guard n?)] :b]              [0xfd 0xcb (b n) 0x18]
         [:rr [:iy (n :guard n?)] :c]              [0xfd 0xcb (b n) 0x19]
         [:rr [:iy (n :guard n?)] :d]              [0xfd 0xcb (b n) 0x1a]
         [:rr [:iy (n :guard n?)] :e]              [0xfd 0xcb (b n) 0x1b]
         [:rr [:iy (n :guard n?)] :h]              [0xfd 0xcb (b n) 0x1c]
         [:rr [:iy (n :guard n?)] :l]              [0xfd 0xcb (b n) 0x1d]
         [:rr [:iy (n :guard n?)]]                 [0xfd 0xcb (b n) 0x1e]
         [:rr [:iy (n :guard n?)] :a]              [0xfd 0xcb (b n) 0x1f]
         [:sla [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x20]
         [:sla [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x21]
         [:sla [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x22]
         [:sla [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x23]
         [:sla [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x24]
         [:sla [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x25]
         [:sla [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x26]
         [:sla [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x27]
         [:sra [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x28]
         [:sra [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x29]
         [:sra [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x2a]
         [:sra [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x2b]
         [:sra [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x2c]
         [:sra [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x2d]
         [:sra [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x2e]
         [:sra [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x2f]
         [:sll [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x30]
         [:sll [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x31]
         [:sll [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x32]
         [:sll [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x33]
         [:sll [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x34]
         [:sll [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x35]
         [:sll [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x36]
         [:sll [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x37]
         [:srl [:iy (n :guard n?)] :b]             [0xfd 0xcb (b n) 0x38]
         [:srl [:iy (n :guard n?)] :c]             [0xfd 0xcb (b n) 0x39]
         [:srl [:iy (n :guard n?)] :d]             [0xfd 0xcb (b n) 0x3a]
         [:srl [:iy (n :guard n?)] :e]             [0xfd 0xcb (b n) 0x3b]
         [:srl [:iy (n :guard n?)] :h]             [0xfd 0xcb (b n) 0x3c]
         [:srl [:iy (n :guard n?)] :l]             [0xfd 0xcb (b n) 0x3d]
         [:srl [:iy (n :guard n?)]]                [0xfd 0xcb (b n) 0x3e]
         [:srl [:iy (n :guard n?)] :a]             [0xfd 0xcb (b n) 0x3f]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x40]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x41]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x42]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x43]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x44]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x45]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x46]
         [:bit 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x47]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x48]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x49]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4a]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4b]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4c]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4d]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4e]
         [:bit 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x4f]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x50]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x51]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x52]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x53]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x54]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x55]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x56]
         [:bit 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x57]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x58]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x59]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5a]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5b]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5c]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5d]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5e]
         [:bit 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x5f]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x60]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x61]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x62]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x63]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x64]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x65]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x66]
         [:bit 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x67]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x68]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x69]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6a]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6b]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6c]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6d]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6e]
         [:bit 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x6f]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x70]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x71]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x72]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x73]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x74]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x75]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x76]
         [:bit 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x77]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x78]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x79]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7a]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7b]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7c]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7d]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7e]
         [:bit 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x7f]
         [:res 0 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0x80]
         [:res 0 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0x81]
         [:res 0 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0x82]
         [:res 0 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0x83]
         [:res 0 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0x84]
         [:res 0 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0x85]
         [:res 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x86]
         [:res 0 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0x87]
         [:res 1 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0x88]
         [:res 1 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0x89]
         [:res 1 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0x8a]
         [:res 1 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0x8b]
         [:res 1 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0x8c]
         [:res 1 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0x8d]
         [:res 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x8e]
         [:res 1 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0x8f]
         [:res 2 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0x90]
         [:res 2 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0x91]
         [:res 2 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0x92]
         [:res 2 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0x93]
         [:res 2 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0x94]
         [:res 2 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0x95]
         [:res 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x96]
         [:res 2 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0x97]
         [:res 3 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0x98]
         [:res 3 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0x99]
         [:res 3 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0x9a]
         [:res 3 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0x9b]
         [:res 3 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0x9c]
         [:res 3 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0x9d]
         [:res 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0x9e]
         [:res 3 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0x9f]
         [:res 4 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xa0]
         [:res 4 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xa1]
         [:res 4 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xa2]
         [:res 4 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xa3]
         [:res 4 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xa4]
         [:res 4 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xa5]
         [:res 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xa6]
         [:res 4 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xa7]
         [:res 5 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xa8]
         [:res 5 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xa9]
         [:res 5 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xaa]
         [:res 5 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xab]
         [:res 5 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xac]
         [:res 5 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xad]
         [:res 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xae]
         [:res 5 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xaf]
         [:res 6 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xb0]
         [:res 6 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xb1]
         [:res 6 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xb2]
         [:res 6 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xb3]
         [:res 6 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xb4]
         [:res 6 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xb5]
         [:res 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xb6]
         [:res 6 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xb7]
         [:res 7 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xb8]
         [:res 7 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xb9]
         [:res 7 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xba]
         [:res 7 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xbb]
         [:res 7 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xbc]
         [:res 7 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xbd]
         [:res 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xbe]
         [:res 7 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xbf]
         [:set 0 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xc0]
         [:set 0 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xc1]
         [:set 0 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xc2]
         [:set 0 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xc3]
         [:set 0 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xc4]
         [:set 0 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xc5]
         [:set 0 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xc6]
         [:set 0 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xc7]
         [:set 1 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xc8]
         [:set 1 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xc9]
         [:set 1 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xca]
         [:set 1 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xcb]
         [:set 1 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xcc]
         [:set 1 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xcd]
         [:set 1 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xce]
         [:set 1 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xcf]
         [:set 2 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xd0]
         [:set 2 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xd1]
         [:set 2 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xd2]
         [:set 2 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xd3]
         [:set 2 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xd4]
         [:set 2 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xd5]
         [:set 2 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xd6]
         [:set 2 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xd7]
         [:set 3 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xd8]
         [:set 3 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xd9]
         [:set 3 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xda]
         [:set 3 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xdb]
         [:set 3 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xdc]
         [:set 3 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xdd]
         [:set 3 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xde]
         [:set 3 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xdf]
         [:set 4 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xe0]
         [:set 4 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xe1]
         [:set 4 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xe2]
         [:set 4 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xe3]
         [:set 4 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xe4]
         [:set 4 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xe5]
         [:set 4 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xe6]
         [:set 4 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xe7]
         [:set 5 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xe8]
         [:set 5 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xe9]
         [:set 5 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xea]
         [:set 5 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xeb]
         [:set 5 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xec]
         [:set 5 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xed]
         [:set 5 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xee]
         [:set 5 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xef]
         [:set 6 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xf0]
         [:set 6 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xf1]
         [:set 6 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xf2]
         [:set 6 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xf3]
         [:set 6 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xf4]
         [:set 6 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xf5]
         [:set 6 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xf6]
         [:set 6 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xf7]
         [:set 7 [:iy (n :guard n?)] :b]           [0xfd 0xcb (b n) 0xf8]
         [:set 7 [:iy (n :guard n?)] :c]           [0xfd 0xcb (b n) 0xf9]
         [:set 7 [:iy (n :guard n?)] :d]           [0xfd 0xcb (b n) 0xfa]
         [:set 7 [:iy (n :guard n?)] :e]           [0xfd 0xcb (b n) 0xfb]
         [:set 7 [:iy (n :guard n?)] :h]           [0xfd 0xcb (b n) 0xfc]
         [:set 7 [:iy (n :guard n?)] :l]           [0xfd 0xcb (b n) 0xfd]
         [:set 7 [:iy (n :guard n?)]]              [0xfd 0xcb (b n) 0xfe]
         [:set 7 [:iy (n :guard n?)] :a]           [0xfd 0xcb (b n) 0xff]
         [:pop :iy]                                [0xfd 0xe1]
         [:ex [:sp] :iy]                           [0xfd 0xe3]
         [:push :iy]                               [0xfd 0xe5]
         [:jp [:iy]]                               [0xfd 0xe9]
         [:ld :sp :iy]                             [0xfd 0xf9]
         :else                                     nil))

(defn assemble-instr-dd
  [instr]
  (match instr
         [:add :ix [:bc]]                          [0xdd 0x09]
         [:add :ix :de]                            [0xdd 0x19]
         [:ld :ix (nn :guard n?)]                  [0xdd 0x21 (lw nn) (hw nn)]
         [:ld [(nn :guard n?)] :ix]                [0xdd 0x22 (lw nn) (hw nn)]
         [:inc :ix]                                [0xdd 0x23]
         [:inc :ixh]                               [0xdd 0x24]
         [:dec :ixh]                               [0xdd 0x25]
         [:ld :ixh (n :guard n?)]                  [0xdd 0x26 (b n)]
         [:add :ix :ix]                            [0xdd 0x29]
         [:ld :ix [(nn :guard n?)]]                [0xdd 0x2a (lw nn) (hw nn)]
         [:dec :ix]                                [0xdd 0x2b]
         [:inc :ixl]                               [0xdd 0x2c]
         [:dec :ixl]                               [0xdd 0x2d]
         [:ld :ixl (n :guard n?)]                  [0xdd 0x2e (b n)]
         [:inc [:ix (n :guard n?)]]                [0xdd 0x34 (b n)]
         [:dec [:ix (n :guard n?)]]                [0xdd 0x35 (b n)]
         [:ld [:ix (n1 :guard n?)] (n2 :guard n?)] [0xdd 0x36 (b n1) (b n2)]
         [:add :ix :sp]                            [0xdd 0x39]
         [:ld :b :ixh]                             [0xdd 0x44]
         [:ld :b :ixl]                             [0xdd 0x45]
         [:ld :b [:ix (n :guard n?)]]              [0xdd 0x46 (b n)]
         [:ld :c :ixh]                             [0xdd 0x4c]
         [:ld :c :ixl]                             [0xdd 0x4d]
         [:ld :c [:ix (n :guard n?)]]              [0xdd 0x4e (b n)]
         [:ld :d :ixh]                             [0xdd 0x54]
         [:ld :d :ixl]                             [0xdd 0x55]
         [:ld :d [:ix (n :guard n?)]]              [0xdd 0x56 (b n)]
         [:ld :e :ixh]                             [0xdd 0x5c]
         [:ld :e :ixl]                             [0xdd 0x5d]
         [:ld :e [:ix (n :guard n?)]]              [0xdd 0x5e (b n)]
         [:ld :ixh :b]                             [0xdd 0x60]
         [:ld :ixh :c]                             [0xdd 0x61]
         [:ld :ixh :d]                             [0xdd 0x62]
         [:ld :ixh :e]                             [0xdd 0x63]
         [:ld :ixh :ixh]                           [0xdd 0x64]
         [:ld :ixh :ixl]                           [0xdd 0x65]
         [:ld :h [:ix (n :guard n?)]]              [0xdd 0x66 (b n)]
         [:ld :ixh :a]                             [0xdd 0x67]
         [:ld :ixl :b]                             [0xdd 0x68]
         [:ld :ixl :c]                             [0xdd 0x69]
         [:ld :ixl :d]                             [0xdd 0x6a]
         [:ld :ixl :e]                             [0xdd 0x6b]
         [:ld :ixl :ixh]                           [0xdd 0x6c]
         [:ld :ixl :ixl]                           [0xdd 0x6d]
         [:ld :l [:ix (n :guard n?)]]              [0xdd 0x6e (b n)]
         [:ld :ixl :a]                             [0xdd 0x6f]
         [:ld [:ix (n :guard n?)] :b]              [0xdd 0x70 (b n)]
         [:ld [:ix (n :guard n?)] :c]              [0xdd 0x71 (b n)]
         [:ld [:ix (n :guard n?)] :d]              [0xdd 0x72 (b n)]
         [:ld [:ix (n :guard n?)] :e]              [0xdd 0x73 (b n)]
         [:ld [:ix (n :guard n?)] :h]              [0xdd 0x74 (b n)]
         [:ld [:ix (n :guard n?)] :l]              [0xdd 0x75 (b n)]
         [:ld [:ix (n :guard n?)] :a]              [0xdd 0x77 (b n)]
         [:ld :a :ixh]                             [0xdd 0x7c]
         [:ld :a :ixl]                             [0xdd 0x7d]
         [:ld :a [:ix (n :guard n?)]]              [0xdd 0x7e (b n)]
         [:add :ixh]                               [0xdd 0x84]
         [:add :ixl]                               [0xdd 0x85]
         [:add [:ix (n :guard n?)]]                [0xdd 0x86 (b n)]
         [:adc :ixh]                               [0xdd 0x8c]
         [:adc :ixl]                               [0xdd 0x8d]
         [:adc [:ix (n :guard n?)]]                [0xdd 0x8e (b n)]
         [:sub :ixh]                               [0xdd 0x94]
         [:sub :ixl]                               [0xdd 0x95]
         [:sub [:ix (n :guard n?)]]                [0xdd 0x96 (b n)]
         [:sbc :ixh]                               [0xdd 0x9c]
         [:sbc :ixl]                               [0xdd 0x9d]
         [:sbc [:ix (n :guard n?)]]                [0xdd 0x9e (b n)]
         [:and :ixh]                               [0xdd 0xa4]
         [:and :ixl]                               [0xdd 0xa5]
         [:and [:ix (n :guard n?)]]                [0xdd 0xa6 (b n)]
         [:xor :ixh]                               [0xdd 0xac]
         [:xor :ixl]                               [0xdd 0xad]
         [:xor [:ix (n :guard n?)]]                [0xdd 0xae (b n)]
         [:or :ixh]                                [0xdd 0xb4]
         [:or :ixl]                                [0xdd 0xb5]
         [:or [:ix (n :guard n?)]]                 [0xdd 0xb6 (b n)]
         [:cp :ixh]                                [0xdd 0xbc]
         [:cp :ixl]                                [0xdd 0xbd]
         [:cp [:ix (n :guard n?)]]                 [0xdd 0xbe (b n)]
         [:rlc [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x00]
         [:rlc [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x01]
         [:rlc [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x02]
         [:rlc [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x03]
         [:rlc [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x04]
         [:rlc [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x05]
         [:rlc [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x06]
         [:rlc [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x07]
         [:rrc [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x08]
         [:rrc [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x09]
         [:rrc [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x0a]
         [:rrc [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x0b]
         [:rrc [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x0c]
         [:rrc [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x0d]
         [:rrc [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x0e]
         [:rrc [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x0f]
         [:rl [:ix (n :guard n?)] :b]              [0xdd 0xcb (b n) 0x10]
         [:rl [:ix (n :guard n?)] :c]              [0xdd 0xcb (b n) 0x11]
         [:rl [:ix (n :guard n?)] :d]              [0xdd 0xcb (b n) 0x12]
         [:rl [:ix (n :guard n?)] :e]              [0xdd 0xcb (b n) 0x13]
         [:rl [:ix (n :guard n?)] :h]              [0xdd 0xcb (b n) 0x14]
         [:rl [:ix (n :guard n?)] :l]              [0xdd 0xcb (b n) 0x15]
         [:rl [:ix (n :guard n?)]]                 [0xdd 0xcb (b n) 0x16]
         [:rl [:ix (n :guard n?)] :a]              [0xdd 0xcb (b n) 0x17]
         [:rr [:ix (n :guard n?)] :b]              [0xdd 0xcb (b n) 0x18]
         [:rr [:ix (n :guard n?)] :c]              [0xdd 0xcb (b n) 0x19]
         [:rr [:ix (n :guard n?)] :d]              [0xdd 0xcb (b n) 0x1a]
         [:rr [:ix (n :guard n?)] :e]              [0xdd 0xcb (b n) 0x1b]
         [:rr [:ix (n :guard n?)] :h]              [0xdd 0xcb (b n) 0x1c]
         [:rr [:ix (n :guard n?)] :l]              [0xdd 0xcb (b n) 0x1d]
         [:rr [:ix (n :guard n?)]]                 [0xdd 0xcb (b n) 0x1e]
         [:rr [:ix (n :guard n?)] :a]              [0xdd 0xcb (b n) 0x1f]
         [:sla [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x20]
         [:sla [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x21]
         [:sla [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x22]
         [:sla [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x23]
         [:sla [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x24]
         [:sla [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x25]
         [:sla [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x26]
         [:sla [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x27]
         [:sra [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x28]
         [:sra [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x29]
         [:sra [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x2a]
         [:sra [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x2b]
         [:sra [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x2c]
         [:sra [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x2d]
         [:sra [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x2e]
         [:sra [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x2f]
         [:sll [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x30]
         [:sll [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x31]
         [:sll [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x32]
         [:sll [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x33]
         [:sll [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x34]
         [:sll [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x35]
         [:sll [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x36]
         [:sll [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x37]
         [:srl [:ix (n :guard n?)] :b]             [0xdd 0xcb (b n) 0x38]
         [:srl [:ix (n :guard n?)] :c]             [0xdd 0xcb (b n) 0x39]
         [:srl [:ix (n :guard n?)] :d]             [0xdd 0xcb (b n) 0x3a]
         [:srl [:ix (n :guard n?)] :e]             [0xdd 0xcb (b n) 0x3b]
         [:srl [:ix (n :guard n?)] :h]             [0xdd 0xcb (b n) 0x3c]
         [:srl [:ix (n :guard n?)] :l]             [0xdd 0xcb (b n) 0x3d]
         [:srl [:ix (n :guard n?)]]                [0xdd 0xcb (b n) 0x3e]
         [:srl [:ix (n :guard n?)] :a]             [0xdd 0xcb (b n) 0x3f]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x40]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x41]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x42]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x43]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x44]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x45]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x46]
         [:bit 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x47]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x48]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x49]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4a]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4b]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4c]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4d]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4e]
         [:bit 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x4f]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x50]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x51]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x52]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x53]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x54]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x55]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x56]
         [:bit 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x57]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x58]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x59]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5a]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5b]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5c]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5d]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5e]
         [:bit 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x5f]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x60]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x61]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x62]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x63]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x64]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x65]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x66]
         [:bit 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x67]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x68]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x69]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6a]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6b]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6c]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6d]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6e]
         [:bit 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x6f]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x70]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x71]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x72]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x73]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x74]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x75]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x76]
         [:bit 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x77]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x78]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x79]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7a]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7b]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7c]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7d]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7e]
         [:bit 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x7f]
         [:res 0 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0x80]
         [:res 0 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0x81]
         [:res 0 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0x82]
         [:res 0 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0x83]
         [:res 0 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0x84]
         [:res 0 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0x85]
         [:res 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x86]
         [:res 0 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0x87]
         [:res 1 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0x88]
         [:res 1 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0x89]
         [:res 1 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0x8a]
         [:res 1 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0x8b]
         [:res 1 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0x8c]
         [:res 1 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0x8d]
         [:res 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x8e]
         [:res 1 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0x8f]
         [:res 2 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0x90]
         [:res 2 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0x91]
         [:res 2 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0x92]
         [:res 2 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0x93]
         [:res 2 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0x94]
         [:res 2 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0x95]
         [:res 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x96]
         [:res 2 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0x97]
         [:res 3 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0x98]
         [:res 3 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0x99]
         [:res 3 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0x9a]
         [:res 3 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0x9b]
         [:res 3 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0x9c]
         [:res 3 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0x9d]
         [:res 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0x9e]
         [:res 3 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0x9f]
         [:res 4 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xa0]
         [:res 4 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xa1]
         [:res 4 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xa2]
         [:res 4 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xa3]
         [:res 4 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xa4]
         [:res 4 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xa5]
         [:res 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xa6]
         [:res 4 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xa7]
         [:res 5 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xa8]
         [:res 5 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xa9]
         [:res 5 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xaa]
         [:res 5 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xab]
         [:res 5 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xac]
         [:res 5 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xad]
         [:res 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xae]
         [:res 5 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xaf]
         [:res 6 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xb0]
         [:res 6 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xb1]
         [:res 6 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xb2]
         [:res 6 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xb3]
         [:res 6 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xb4]
         [:res 6 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xb5]
         [:res 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xb6]
         [:res 6 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xb7]
         [:res 7 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xb8]
         [:res 7 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xb9]
         [:res 7 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xba]
         [:res 7 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xbb]
         [:res 7 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xbc]
         [:res 7 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xbd]
         [:res 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xbe]
         [:res 7 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xbf]
         [:set 0 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xc0]
         [:set 0 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xc1]
         [:set 0 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xc2]
         [:set 0 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xc3]
         [:set 0 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xc4]
         [:set 0 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xc5]
         [:set 0 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xc6]
         [:set 0 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xc7]
         [:set 1 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xc8]
         [:set 1 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xc9]
         [:set 1 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xca]
         [:set 1 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xcb]
         [:set 1 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xcc]
         [:set 1 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xcd]
         [:set 1 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xce]
         [:set 1 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xcf]
         [:set 2 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xd0]
         [:set 2 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xd1]
         [:set 2 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xd2]
         [:set 2 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xd3]
         [:set 2 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xd4]
         [:set 2 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xd5]
         [:set 2 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xd6]
         [:set 2 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xd7]
         [:set 3 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xd8]
         [:set 3 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xd9]
         [:set 3 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xda]
         [:set 3 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xdb]
         [:set 3 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xdc]
         [:set 3 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xdd]
         [:set 3 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xde]
         [:set 3 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xdf]
         [:set 4 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xe0]
         [:set 4 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xe1]
         [:set 4 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xe2]
         [:set 4 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xe3]
         [:set 4 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xe4]
         [:set 4 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xe5]
         [:set 4 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xe6]
         [:set 4 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xe7]
         [:set 5 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xe8]
         [:set 5 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xe9]
         [:set 5 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xea]
         [:set 5 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xeb]
         [:set 5 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xec]
         [:set 5 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xed]
         [:set 5 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xee]
         [:set 5 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xef]
         [:set 6 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xf0]
         [:set 6 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xf1]
         [:set 6 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xf2]
         [:set 6 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xf3]
         [:set 6 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xf4]
         [:set 6 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xf5]
         [:set 6 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xf6]
         [:set 6 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xf7]
         [:set 7 [:ix (n :guard n?)] :b]           [0xdd 0xcb (b n) 0xf8]
         [:set 7 [:ix (n :guard n?)] :c]           [0xdd 0xcb (b n) 0xf9]
         [:set 7 [:ix (n :guard n?)] :d]           [0xdd 0xcb (b n) 0xfa]
         [:set 7 [:ix (n :guard n?)] :e]           [0xdd 0xcb (b n) 0xfb]
         [:set 7 [:ix (n :guard n?)] :h]           [0xdd 0xcb (b n) 0xfc]
         [:set 7 [:ix (n :guard n?)] :l]           [0xdd 0xcb (b n) 0xfd]
         [:set 7 [:ix (n :guard n?)]]              [0xdd 0xcb (b n) 0xfe]
         [:set 7 [:ix (n :guard n?)] :a]           [0xdd 0xcb (b n) 0xff]
         [:pop :ix]                                [0xdd 0xe1]
         [:ex [:sp] :ix]                           [0xdd 0xe3]
         [:push :ix]                               [0xdd 0xe5]
         [:jp [:ix]]                               [0xdd 0xe9]
         [:ld :sp :ix]                             [0xdd 0xf9]
         :else                                     nil))

(defn assemble-instr-cb
  [instr]
  (match instr
    [:rlc :b]      [0xcb 0x00]
    [:rlc :c]      [0xcb 0x01]
    [:rlc :d]      [0xcb 0x02]
    [:rlc :e]      [0xcb 0x03]
    [:rlc :h]      [0xcb 0x04]
    [:rlc :l]      [0xcb 0x05]
    [:rlc [:hl]]   [0xcb 0x06]
    [:rlc :a]      [0xcb 0x07]
    [:rrc :b]      [0xcb 0x08]
    [:rrc :c]      [0xcb 0x09]
    [:rrc :d]      [0xcb 0x0a]
    [:rrc :e]      [0xcb 0x0b]
    [:rrc :h]      [0xcb 0x0c]
    [:rrc :l]      [0xcb 0x0d]
    [:rrc [:hl]]   [0xcb 0x0e]
    [:rrc :a]      [0xcb 0x0f]
    [:rl :b]       [0xcb 0x10]
    [:rl :c]       [0xcb 0x11]
    [:rl :d]       [0xcb 0x12]
    [:rl :e]       [0xcb 0x13]
    [:rl :h]       [0xcb 0x14]
    [:rl :l]       [0xcb 0x15]
    [:rl [:hl]]    [0xcb 0x16]
    [:rl :a]       [0xcb 0x17]
    [:rr :b]       [0xcb 0x18]
    [:rr :c]       [0xcb 0x19]
    [:rr :d]       [0xcb 0x1a]
    [:rr :e]       [0xcb 0x1b]
    [:rr :h]       [0xcb 0x1c]
    [:rr :l]       [0xcb 0x1d]
    [:rr [:hl]]    [0xcb 0x1e]
    [:rr :a]       [0xcb 0x1f]
    [:sla :b]      [0xcb 0x20]
    [:sla :c]      [0xcb 0x21]
    [:sla :d]      [0xcb 0x22]
    [:sla :e]      [0xcb 0x23]
    [:sla :h]      [0xcb 0x24]
    [:sla :l]      [0xcb 0x25]
    [:sla [:hl]]   [0xcb 0x26]
    [:sla :a]      [0xcb 0x27]
    [:sra :b]      [0xcb 0x28]
    [:sra :c]      [0xcb 0x29]
    [:sra :d]      [0xcb 0x2a]
    [:sra :e]      [0xcb 0x2b]
    [:sra :h]      [0xcb 0x2c]
    [:sra :l]      [0xcb 0x2d]
    [:sra [:hl]]   [0xcb 0x2e]
    [:sra :a]      [0xcb 0x2f]
    [:sll :b]      [0xcb 0x30]
    [:sll :c]      [0xcb 0x31]
    [:sll :d]      [0xcb 0x32]
    [:sll :e]      [0xcb 0x33]
    [:sll :h]      [0xcb 0x34]
    [:sll :l]      [0xcb 0x35]
    [:sll [:hl]]   [0xcb 0x36]
    [:sll :a]      [0xcb 0x37]
    [:srl :b]      [0xcb 0x38]
    [:srl :c]      [0xcb 0x39]
    [:srl :d]      [0xcb 0x3a]
    [:srl :e]      [0xcb 0x3b]
    [:srl :h]      [0xcb 0x3c]
    [:srl :l]      [0xcb 0x3d]
    [:srl [:hl]]   [0xcb 0x3e]
    [:srl :a]      [0xcb 0x3f]
    [:bit 0 :b]    [0xcb 0x40]
    [:bit 0 :c]    [0xcb 0x41]
    [:bit 0 :d]    [0xcb 0x42]
    [:bit 0 :e]    [0xcb 0x43]
    [:bit 0 :h]    [0xcb 0x44]
    [:bit 0 :l]    [0xcb 0x45]
    [:bit 0 [:hl]] [0xcb 0x46]
    [:bit 0 :a]    [0xcb 0x47]
    [:bit 1 :b]    [0xcb 0x48]
    [:bit 1 :c]    [0xcb 0x49]
    [:bit 1 :d]    [0xcb 0x4a]
    [:bit 1 :e]    [0xcb 0x4b]
    [:bit 1 :h]    [0xcb 0x4c]
    [:bit 1 :l]    [0xcb 0x4d]
    [:bit 1 [:hl]] [0xcb 0x4e]
    [:bit 1 :a]    [0xcb 0x4f]
    [:bit 2 :b]    [0xcb 0x50]
    [:bit 2 :c]    [0xcb 0x51]
    [:bit 2 :d]    [0xcb 0x52]
    [:bit 2 :e]    [0xcb 0x53]
    [:bit 2 :h]    [0xcb 0x54]
    [:bit 2 :l]    [0xcb 0x55]
    [:bit 2 [:hl]] [0xcb 0x56]
    [:bit 2 :a]    [0xcb 0x57]
    [:bit 3 :b]    [0xcb 0x58]
    [:bit 3 :c]    [0xcb 0x59]
    [:bit 3 :d]    [0xcb 0x5a]
    [:bit 3 :e]    [0xcb 0x5b]
    [:bit 3 :h]    [0xcb 0x5c]
    [:bit 3 :l]    [0xcb 0x5d]
    [:bit 3 [:hl]] [0xcb 0x5e]
    [:bit 3 :a]    [0xcb 0x5f]
    [:bit 4 :b]    [0xcb 0x60]
    [:bit 4 :c]    [0xcb 0x61]
    [:bit 4 :d]    [0xcb 0x62]
    [:bit 4 :e]    [0xcb 0x63]
    [:bit 4 :h]    [0xcb 0x64]
    [:bit 4 :l]    [0xcb 0x65]
    [:bit 4 [:hl]] [0xcb 0x66]
    [:bit 4 :a]    [0xcb 0x67]
    [:bit 5 :b]    [0xcb 0x68]
    [:bit 5 :c]    [0xcb 0x69]
    [:bit 5 :d]    [0xcb 0x6a]
    [:bit 5 :e]    [0xcb 0x6b]
    [:bit 5 :h]    [0xcb 0x6c]
    [:bit 5 :l]    [0xcb 0x6d]
    [:bit 5 [:hl]] [0xcb 0x6e]
    [:bit 5 :a]    [0xcb 0x6f]
    [:bit 6 :b]    [0xcb 0x70]
    [:bit 6 :c]    [0xcb 0x71]
    [:bit 6 :d]    [0xcb 0x72]
    [:bit 6 :e]    [0xcb 0x73]
    [:bit 6 :h]    [0xcb 0x74]
    [:bit 6 :l]    [0xcb 0x75]
    [:bit 6 [:hl]] [0xcb 0x76]
    [:bit 6 :a]    [0xcb 0x77]
    [:bit 7 :b]    [0xcb 0x78]
    [:bit 7 :c]    [0xcb 0x79]
    [:bit 7 :d]    [0xcb 0x7a]
    [:bit 7 :e]    [0xcb 0x7b]
    [:bit 7 :h]    [0xcb 0x7c]
    [:bit 7 :l]    [0xcb 0x7d]
    [:bit 7 [:hl]] [0xcb 0x7e]
    [:bit 7 :a]    [0xcb 0x7f]
    [:res 0 :b]    [0xcb 0x80]
    [:res 0 :c]    [0xcb 0x81]
    [:res 0 :d]    [0xcb 0x82]
    [:res 0 :e]    [0xcb 0x83]
    [:res 0 :h]    [0xcb 0x84]
    [:res 0 :l]    [0xcb 0x85]
    [:res 0 [:hl]] [0xcb 0x86]
    [:res 0 :a]    [0xcb 0x87]
    [:res 1 :b]    [0xcb 0x88]
    [:res 1 :c]    [0xcb 0x89]
    [:res 1 :d]    [0xcb 0x8a]
    [:res 1 :e]    [0xcb 0x8b]
    [:res 1 :h]    [0xcb 0x8c]
    [:res 1 :l]    [0xcb 0x8d]
    [:res 1 [:hl]] [0xcb 0x8e]
    [:res 1 :a]    [0xcb 0x8f]
    [:res 2 :b]    [0xcb 0x90]
    [:res 2 :c]    [0xcb 0x91]
    [:res 2 :d]    [0xcb 0x92]
    [:res 2 :e]    [0xcb 0x93]
    [:res 2 :h]    [0xcb 0x94]
    [:res 2 :l]    [0xcb 0x95]
    [:res 2 [:hl]] [0xcb 0x96]
    [:res 2 :a]    [0xcb 0x97]
    [:res 3 :b]    [0xcb 0x98]
    [:res 3 :c]    [0xcb 0x99]
    [:res 3 :d]    [0xcb 0x9a]
    [:res 3 :e]    [0xcb 0x9b]
    [:res 3 :h]    [0xcb 0x9c]
    [:res 3 :l]    [0xcb 0x9d]
    [:res 3 [:hl]] [0xcb 0x9e]
    [:res 3 :a]    [0xcb 0x9f]
    [:res 4 :b]    [0xcb 0xa0]
    [:res 4 :c]    [0xcb 0xa1]
    [:res 4 :d]    [0xcb 0xa2]
    [:res 4 :e]    [0xcb 0xa3]
    [:res 4 :h]    [0xcb 0xa4]
    [:res 4 :l]    [0xcb 0xa5]
    [:res 4 [:hl]] [0xcb 0xa6]
    [:res 4 :a]    [0xcb 0xa7]
    [:res 5 :b]    [0xcb 0xa8]
    [:res 5 :c]    [0xcb 0xa9]
    [:res 5 :d]    [0xcb 0xaa]
    [:res 5 :e]    [0xcb 0xab]
    [:res 5 :h]    [0xcb 0xac]
    [:res 5 :l]    [0xcb 0xad]
    [:res 5 [:hl]] [0xcb 0xae]
    [:res 5 :a]    [0xcb 0xaf]
    [:res 6 :b]    [0xcb 0xb0]
    [:res 6 :c]    [0xcb 0xb1]
    [:res 6 :d]    [0xcb 0xb2]
    [:res 6 :e]    [0xcb 0xb3]
    [:res 6 :h]    [0xcb 0xb4]
    [:res 6 :l]    [0xcb 0xb5]
    [:res 6 [:hl]] [0xcb 0xb6]
    [:res 6 :a]    [0xcb 0xb7]
    [:res 7 :b]    [0xcb 0xb8]
    [:res 7 :c]    [0xcb 0xb9]
    [:res 7 :d]    [0xcb 0xba]
    [:res 7 :e]    [0xcb 0xbb]
    [:res 7 :h]    [0xcb 0xbc]
    [:res 7 :l]    [0xcb 0xbd]
    [:res 7 [:hl]] [0xcb 0xbe]
    [:res 7 :a]    [0xcb 0xbf]
    [:set 0 :b]    [0xcb 0xc0]
    [:set 0 :c]    [0xcb 0xc1]
    [:set 0 :d]    [0xcb 0xc2]
    [:set 0 :e]    [0xcb 0xc3]
    [:set 0 :h]    [0xcb 0xc4]
    [:set 0 :l]    [0xcb 0xc5]
    [:set 0 [:hl]] [0xcb 0xc6]
    [:set 0 :a]    [0xcb 0xc7]
    [:set 1 :b]    [0xcb 0xc8]
    [:set 1 :c]    [0xcb 0xc9]
    [:set 1 :d]    [0xcb 0xca]
    [:set 1 :e]    [0xcb 0xcb]
    [:set 1 :h]    [0xcb 0xcc]
    [:set 1 :l]    [0xcb 0xcd]
    [:set 1 [:hl]] [0xcb 0xce]
    [:set 1 :a]    [0xcb 0xcf]
    [:set 2 :b]    [0xcb 0xd0]
    [:set 2 :c]    [0xcb 0xd1]
    [:set 2 :d]    [0xcb 0xd2]
    [:set 2 :e]    [0xcb 0xd3]
    [:set 2 :h]    [0xcb 0xd4]
    [:set 2 :l]    [0xcb 0xd5]
    [:set 2 [:hl]] [0xcb 0xd6]
    [:set 2 :a]    [0xcb 0xd7]
    [:set 3 :b]    [0xcb 0xd8]
    [:set 3 :c]    [0xcb 0xd9]
    [:set 3 :d]    [0xcb 0xda]
    [:set 3 :e]    [0xcb 0xdb]
    [:set 3 :h]    [0xcb 0xdc]
    [:set 3 :l]    [0xcb 0xdd]
    [:set 3 [:hl]] [0xcb 0xde]
    [:set 3 :a]    [0xcb 0xdf]
    [:set 4 :b]    [0xcb 0xe0]
    [:set 4 :c]    [0xcb 0xe1]
    [:set 4 :d]    [0xcb 0xe2]
    [:set 4 :e]    [0xcb 0xe3]
    [:set 4 :h]    [0xcb 0xe4]
    [:set 4 :l]    [0xcb 0xe5]
    [:set 4 [:hl]] [0xcb 0xe6]
    [:set 4 :a]    [0xcb 0xe7]
    [:set 5 :b]    [0xcb 0xe8]
    [:set 5 :c]    [0xcb 0xe9]
    [:set 5 :d]    [0xcb 0xea]
    [:set 5 :e]    [0xcb 0xeb]
    [:set 5 :h]    [0xcb 0xec]
    [:set 5 :l]    [0xcb 0xed]
    [:set 5 [:hl]] [0xcb 0xee]
    [:set 5 :a]    [0xcb 0xef]
    [:set 6 :b]    [0xcb 0xf0]
    [:set 6 :c]    [0xcb 0xf1]
    [:set 6 :d]    [0xcb 0xf2]
    [:set 6 :e]    [0xcb 0xf3]
    [:set 6 :h]    [0xcb 0xf4]
    [:set 6 :l]    [0xcb 0xf5]
    [:set 6 [:hl]] [0xcb 0xf6]
    [:set 6 :a]    [0xcb 0xf7]
    [:set 7 :b]    [0xcb 0xf8]
    [:set 7 :c]    [0xcb 0xf9]
    [:set 7 :d]    [0xcb 0xfa]
    [:set 7 :e]    [0xcb 0xfb]
    [:set 7 :h]    [0xcb 0xfc]
    [:set 7 :l]    [0xcb 0xfd]
    [:set 7 [:hl]] [0xcb 0xfe]
    [:set 7 :a]    [0xcb 0xff]
    :else          nil))

(defn assemble-instr-ed
  [instr]
  (match instr
         [:in :b [:c]]                [0xed 0x40]
         [:out [:c] :b]               [0xed 0x41]
         [:sbc :hl :bc]               [0xed 0x42]
         [:ld [(nn :guard n?)] :bc]   [0xed 0x43 (lw nn) (hw nn)]
         [:neg]                       [0xed 0x44]
         [:retn]                      [0xed 0x45]
         [:im 0]                      [0xed 0x46]
         [:ld i :a]                   [0xed 0x47]
         [:in :c [:c]]                [0xed 0x48]
         [:out [:c] :c]               [0xed 0x49]
         [:adc :hl :bc]               [0xed 0x4a]
         [:ld :bc [(nn :guard n?)]]   [0xed 0x4b (lw nn) (hw nn)]
         [:neg]                       [0xed 0x4c]
         [:reti]                      [0xed 0x4d]
         [:im 0]                      [0xed 0x4e]
         [:ld r :a]                   [0xed 0x4f]
         [:in :d [:c]]                [0xed 0x50]
         [:out [:c] :d]               [0xed 0x51]
         [:sbc :hl :de]               [0xed 0x52]
         [:ld [(nn :guard n?)] :de]   [0xed 0x53 (lw nn) (hw nn)]
         [:neg]                       [0xed 0x54]
         [:retn]                      [0xed 0x55]
         [:im 1]                      [0xed 0x56]
         [:ld :a i]                   [0xed 0x57]
         [:in :e [:c]]                [0xed 0x58]
         [:out [:c] :e]               [0xed 0x59]
         [:adc :hl :de]               [0xed 0x5a]
         [:ld :de [(nn :guard n?)]]   [0xed 0x5b (lw nn) (hw nn)]
         [:neg]                       [0xed 0x5c]
         [:retn]                      [0xed 0x5d]
         [:im 2]                      [0xed 0x5e]
         [:ld :a r]                   [0xed 0x5f]
         [:in :h [:c]]                [0xed 0x60]
         [:out [:c] :h]               [0xed 0x61]
         [:sbc :hl :hl]               [0xed 0x62]
         [:ld [(nn :guard n?)] :hl]   [0xed 0x63 (lw nn) (hw nn)]
         [:neg]                       [0xed 0x64]
         [:retn]                      [0xed 0x65]
         [:im 0]                      [0xed 0x66]
         [:rrd]                       [0xed 0x67]
         [:in :l [:c]]                [0xed 0x68]
         [:out [:c] :l]               [0xed 0x69]
         [:adc :hl :hl]               [0xed 0x6a]
         [:ld :hl [(nn :guard n?)]]   [0xed 0x6b (lw nn) (hw nn)]
         [:neg]                       [0xed 0x6c]
         [:retn]                      [0xed 0x6d]
         [:im 0]                      [0xed 0x6e]
         [:rld]                       [0xed 0x6f]
         [:in [:c]]                   [0xed 0x70]
         [:out [:c] 0]                [0xed 0x71]
         [:sbc :hl :sp]               [0xed 0x72]
         [:ld [(nn :guard n?)] :sp]   [0xed 0x73 (lw nn) (hw nn)]
         [:neg]                       [0xed 0x74]
         [:retn]                      [0xed 0x75]
         [:im 1]                      [0xed 0x76]
         [:in :a [:c]]                [0xed 0x78]
         [:out [:c] :a]               [0xed 0x79]
         [:adc :hl :sp]               [0xed 0x7a]
         [:ld :sp [(nn :guard n?)]]   [0xed 0x7b (lw nn) (hw nn)]
         [:neg]                       [0xed 0x7c]
         [:retn]                      [0xed 0x7d]
         [:im 2]                      [0xed 0x7e]
         [:ldi]                       [0xed 0xa0]
         [:cpi]                       [0xed 0xa1]
         [:ini]                       [0xed 0xa2]
         [:outi]                      [0xed 0xa3]
         [:ldd]                       [0xed 0xa8]
         [:cpd]                       [0xed 0xa9]
         [:ind]                       [0xed 0xaa]
         [:outd]                      [0xed 0xab]
         [:ldir]                      [0xed 0xb0]
         [:cpir]                      [0xed 0xb1]
         [:inir]                      [0xed 0xb2]
         [:otir]                      [0xed 0xb3]
         [:lddr]                      [0xed 0xb8]
         [:cpdr]                      [0xed 0xb9]
         [:indr]                      [0xed 0xba]
         [:otdr]                      [0xed 0xbb]
         [:xor (n :guard n?)]         [0xee (b n)]
         :else                        nil))

(defn assemble-instr-base
  [instr]
  (match instr
         [:nop]                     [0x00]
         [:ld :bc (nn :guard n?)]   [0x01 (lw nn) (hw nn)]
         [:ld [:bc] :a]             [0x02]
         [:inc :bc]                 [0x03]
         [:inc :b]                  [0x04]
         [:dec :b]                  [0x05]
         [:ld :b (n :guard n?)]     [0x06 (b n)]
         [:rlca]                    [0x07]
         [:ex :af :af]              [0x08]
         [:add :hl :bc]             [0x09]
         [:ld :a [:bc]]             [0x0a]
         [:dec :bc]                 [0x0b]
         [:inc :c]                  [0x0c]
         [:dec :c]                  [0x0d]
         [:ld :c (n :guard n?)]     [0x0e (b n)]
         [:rrca]                    [0x0f]
         [:djnz (n :guard n?)]      [0x10 (e n)]
         [:ld :de (nn :guard n?)]   [0x11 (lw nn) (hw nn)]
         [:ld [:de] :a]             [0x12]
         [:inc :de]                 [0x13]
         [:inc :d]                  [0x14]
         [:dec :d]                  [0x15]
         [:ld :d (n :guard n?)]     [0x16 (b n)]
         [:rla]                     [0x17]
         [:jr (n :guard n?)]        [0x18 (e n)]
         [:add :hl :de]             [0x19]
         [:ld :a [:de]]             [0x1a]
         [:dec :de]                 [0x1b]
         [:inc :e]                  [0x1c]
         [:dec :e]                  [0x1d]
         [:ld :e (n :guard n?)]     [0x1e (b n)]
         [:rra]                     [0x1f]
         [:jr :nz (n :guard n?)]    [0x20 (e n)]
         [:ld :hl (nn :guard n?)]   [0x21 (lw nn) (hw nn)]
         [:ld [(nn :guard n?)] :hl] [0x22 (lw nn) (hw nn)]
         [:inc :hl]                 [0x23]
         [:inc :h]                  [0x24]
         [:dec :h]                  [0x25]
         [:ld :h (n :guard n?)]     [0x26 (b n)]
         [:daa]                     [0x27]
         [:jr :z (n :guard n?)]     [0x28 (e n)]
         [:add :hl :hl]             [0x29]
         [:ld :hl [(nn :guard n?)]] [0x2a (lw nn) (hw nn)]
         [:dec :hl]                 [0x2b]
         [:inc :l]                  [0x2c]
         [:dec :l]                  [0x2d]
         [:ld :l (n :guard n?)]     [0x2e (b n)]
         [:cpl]                     [0x2f]
         [:jr :nc (n :guard n?)]    [0x30 (e n)]
         [:ld :sp (nn :guard n?)]   [0x31 (lw nn) (hw nn)]
         [:ld [(nn :guard n?)] :a]  [0x32 (lw nn) (hw nn)]
         [:inc :sp]                 [0x33]
         [:inc [:hl]]               [0x34]
         [:dec [:hl]]               [0x35]
         [:ld [:hl] (n :guard n?)]  [0x36 (b n)]
         [:scf]                     [0x37]
         [:jr :c (n :guard n?)]     [0x38 (e n)]
         [:add :hl :sp]             [0x39]
         [:ld :a [(nn :guard n?)]]  [0x3a (lw nn) (hw nn)]
         [:dec :sp]                 [0x3b]
         [:inc :a]                  [0x3c]
         [:dec :a]                  [0x3d]
         [:ld :a (n :guard n?)]     [0x3e (b n)]
         [:ccf]                     [0x3f]
         [:ld :b :b]                [0x40]
         [:ld :b :c]                [0x41]
         [:ld :b :d]                [0x42]
         [:ld :b :e]                [0x43]
         [:ld :b :h]                [0x44]
         [:ld :b :l]                [0x45]
         [:ld :b [:hl]]             [0x46]
         [:ld :b :a]                [0x47]
         [:ld :c :b]                [0x48]
         [:ld :c :c]                [0x49]
         [:ld :c :d]                [0x4a]
         [:ld :c :e]                [0x4b]
         [:ld :c :h]                [0x4c]
         [:ld :c :l]                [0x4d]
         [:ld :c [:hl]]             [0x4e]
         [:ld :c :a]                [0x4f]
         [:ld :d :b]                [0x50]
         [:ld :d :c]                [0x51]
         [:ld :d :d]                [0x52]
         [:ld :d :e]                [0x53]
         [:ld :d :h]                [0x54]
         [:ld :d :l]                [0x55]
         [:ld :d [:hl]]             [0x56]
         [:ld :d :a]                [0x57]
         [:ld :e :b]                [0x58]
         [:ld :e :c]                [0x59]
         [:ld :e :d]                [0x5a]
         [:ld :e :e]                [0x5b]
         [:ld :e :h]                [0x5c]
         [:ld :e :l]                [0x5d]
         [:ld :e [:hl]]             [0x5e]
         [:ld :e :a]                [0x5f]
         [:ld :h :b]                [0x60]
         [:ld :h :c]                [0x61]
         [:ld :h :d]                [0x62]
         [:ld :h :e]                [0x63]
         [:ld :h :h]                [0x64]
         [:ld :h :l]                [0x65]
         [:ld :h [:hl]]             [0x66]
         [:ld :h :a]                [0x67]
         [:ld :l :b]                [0x68]
         [:ld :l :c]                [0x69]
         [:ld :l :d]                [0x6a]
         [:ld :l :e]                [0x6b]
         [:ld :l :h]                [0x6c]
         [:ld :l :l]                [0x6d]
         [:ld :l [:hl]]             [0x6e]
         [:ld :l :a]                [0x6f]
         [:ld [:hl] :b]             [0x70]
         [:ld [:hl] :c]             [0x71]
         [:ld [:hl] :d]             [0x72]
         [:ld [:hl] :e]             [0x73]
         [:ld [:hl] :h]             [0x74]
         [:ld [:hl] :l]             [0x75]
         [:halt]                    [0x76]
         [:ld [:hl] :a]             [0x77]
         [:ld :a :b]                [0x78]
         [:ld :a :c]                [0x79]
         [:ld :a :d]                [0x7a]
         [:ld :a :e]                [0x7b]
         [:ld :a :h]                [0x7c]
         [:ld :a :l]                [0x7d]
         [:ld :a [:hl]]             [0x7e]
         [:ld :a :a]                [0x7f]
         [:add :b]                  [0x80]
         [:add :c]                  [0x81]
         [:add :d]                  [0x82]
         [:add :e]                  [0x83]
         [:add :h]                  [0x84]
         [:add :l]                  [0x85]
         [:add [:hl]]               [0x86]
         [:add :a]                  [0x87]
         [:adc :b]                  [0x88]
         [:adc :c]                  [0x89]
         [:adc :d]                  [0x8a]
         [:adc :e]                  [0x8b]
         [:adc :h]                  [0x8c]
         [:adc :l]                  [0x8d]
         [:adc [:hl]]               [0x8e]
         [:adc :a]                  [0x8f]
         [:sub :b]                  [0x90]
         [:sub :c]                  [0x91]
         [:sub :d]                  [0x92]
         [:sub :e]                  [0x93]
         [:sub :h]                  [0x94]
         [:sub :l]                  [0x95]
         [:sub [:hl]]               [0x96]
         [:sub :a]                  [0x97]
         [:sbc :b]                  [0x98]
         [:sbc :c]                  [0x99]
         [:sbc :d]                  [0x9a]
         [:sbc :e]                  [0x9b]
         [:sbc :h]                  [0x9c]
         [:sbc :l]                  [0x9d]
         [:sbc [:hl]]               [0x9e]
         [:sbc :a]                  [0x9f]
         [:and :b]                  [0xa0]
         [:and :c]                  [0xa1]
         [:and :d]                  [0xa2]
         [:and :e]                  [0xa3]
         [:and :h]                  [0xa4]
         [:and :l]                  [0xa5]
         [:and [:hl]]               [0xa6]
         [:and :a]                  [0xa7]
         [:xor :b]                  [0xa8]
         [:xor :c]                  [0xa9]
         [:xor :d]                  [0xaa]
         [:xor :e]                  [0xab]
         [:xor :h]                  [0xac]
         [:xor :l]                  [0xad]
         [:xor [:hl]]               [0xae]
         [:xor :a]                  [0xaf]
         [:or :b]                   [0xb0]
         [:or :c]                   [0xb1]
         [:or :d]                   [0xb2]
         [:or :e]                   [0xb3]
         [:or :h]                   [0xb4]
         [:or :l]                   [0xb5]
         [:or [:hl]]                [0xb6]
         [:or :a]                   [0xb7]
         [:cp :b]                   [0xb8]
         [:cp :c]                   [0xb9]
         [:cp :d]                   [0xba]
         [:cp :e]                   [0xbb]
         [:cp :h]                   [0xbc]
         [:cp :l]                   [0xbd]
         [:cp [:hl]]                [0xbe]
         [:cp :a]                   [0xbf]
         [:ret :nz]                 [0xc0]
         [:pop :bc]                 [0xc1]
         [:jp :nz (nn :guard n?)]   [0xc2 (lw nn) (hw nn)]
         [:jp (nn :guard n?)]       [0xc3 (lw nn) (hw nn)]
         [:call :nz (nn :guard n?)] [0xc4 (lw nn) (hw nn)]
         [:push :bc]                [0xc5]
         [:add (n :guard n?)]       [0xc6 (b n)]
         [:rst 0x00]                [0xc7]
         [:ret :z]                  [0xc8]
         [:ret]                     [0xc9]
         [:jp :z (nn :guard n?)]    [0xca (lw nn) (hw nn)]
         [:call :z (nn :guard n?)]  [0xcc (lw nn) (hw nn)]
         [:call (nn :guard n?)]     [0xcd (lw nn) (hw nn)]
         [:adc :a (n :guard n?)]    [0xce (b n)]
         [:rst 0x08]                [0xcf]
         [:ret :nc]                 [0xd0]
         [:pop :de]                 [0xd1]
         [:jp :nc (nn :guard n?)]   [0xd2 (lw nn) (hw nn)]
         [:out [(n :guard n?)] :a]  [0xd3 (b n)]
         [:call :nc (nn :guard n?)] [0xd4 (lw nn) (hw nn)]
         [:push :de]                [0xd5]
         [:sub :a (n :guard n?)]    [0xd6 (b n)]
         [:rst 0x10]                [0xd7]
         [:ret :c]                  [0xd8]
         [:exx]                     [0xd9]
         [:jp :c (nn :guard n?)]    [0xda (lw nn) (hw nn)]
         [:in :a [(n :guard n?)]]   [0xdb (b n)]
         [:call :c (nn :guard n?)]  [0xdc (lw nn) (hw nn)]
         [:sbc (n :guard n?)]       [0xde (b n)]
         [:rst 0x18]                [0xdf]
         [:ret :po]                 [0xe0]
         [:pop :hl]                 [0xe1]
         [:jp :po (nn :guard n?)]   [0xe2 (lw nn) (hw nn)]
         [:ex [:sp] :hl]            [0xe3]
         [:call :po (nn :guard n?)] [0xe4 (lw nn) (hw nn)]
         [:push :hl]                [0xe5]
         [:and (n :guard n?)]       [0xe6 (b n)]
         [:rst 0x20]                [0xe7]
         [:ret :pe]                 [0xe8]
         [:jp [:hl]]                [0xe9]
         [:jp :pe (nn :guard n?)]   [0xea (lw nn) (hw nn)]
         [:ex :de :hl]              [0xeb]
         [:call :pe (nn :guard n?)] [0xec (lw nn) (hw nn)]
         [:xor (n :guard n?)]       [0xee (b n)]
         [:rst 0x28]                [0xef]
         [:ret :pc]                 [0xf0]
         [:pop :af]                 [0xf1]
         [:jp :pc (nn :guard n?)]   [0xf2 (lw nn) (hw nn)]
         [:di]                      [0xf3]
         [:call :pc (nn :guard n?)] [0xf4 (lw nn) (hw nn)]
         [:push :af]                [0xf5]
         [:or (n :guard n?)]        [0xf6 (b n)]
         [:rst 0x30]                [0xf7]
         [:ret :m]                  [0xf8]
         [:ld :sp :hl]              [0xf9]
         [:jp :m (nn :guard n?)]    [0xfa (lw nn) (hw nn)]
         [:ei]                      [0xfb]
         [:call :m (nn :guard n?)]  [0xfc (lw nn) (hw nn)]
         [:cp (n :guard n?)]        [0xfe (b n)]
         [:rst 0x38]                [0xff]
         [:db (n :guard n?)]        [n]
         [:db (r :guard
                 (fn [n]
                   (and (not (n? n))
                        (coll? n))))] (map b r)
         :else                      nil))

(defn assemble-instr
  [instr]
  (or (assemble-instr-base instr)
      (assemble-instr-fd instr)
      (assemble-instr-dd instr)
      (assemble-instr-cb instr)
      (assemble-instr-ed instr)
      (throw (Exception. (str "Unknown opcode " instr)))))

(defn assemble-instrs
  [instrs]
  (mapcat assemble-instr instrs))
